package attacks.traditional;

import crypto.traditional.FourSquareCipher;
import org.junit.jupiter.api.Test;
import util.Stopwatch;
import util.TextFitnessCalculator;

import static org.junit.jupiter.api.Assertions.assertTrue;

class FourSquareCipherSolverTest {

    @Test
    void testFindKey() {
        System.out.println("FourSquareCipherSolverTest.java: Test is started.");
        String plaintext = "THEFIRSTSIXTYCHARACTERSISTHESOLUTIONITHANKTHEACMFORTHISAWARDICANTHELPBUTFEELTHATIAMRECEIVINGTHISHONORFORTIMINGANDSERENDIPITYASMUCHASTECHNICALMERITUNIXSWEPTINTOPOPULARITYWITHANINDUSTRYWIDECHANGEFROMCENTRALMAINFRAMESTOAUTONOMOUSMINISISUSPECTXHATDANIELBOBROWXOULDBEHEREINSTEADOFMEIFHECOULDNOTAFXORDAPDPANDHADHADTOSETXLEFORAPDPMOREOVERTHECURXENTSTATEOFUNIXISTHERESULTOFTHELABORSOFALARGENUMBEROFPEOPLETHEREISANOLDADAGEDANCEWITHTHEONETHATBROUGHTYOUWHICHMEANSTHATISHOULDTALKABOUTUNIXIHAVENOTWORKEDONMAINSTREAMUNIXINMANYYEARSYETICONTINUETOGETUNDESERVEDCREDITFORTHEWORKOFOTHERSTHEREFOREIAMNOTGOINGTOTALKABOUTUNIXBUTIWANTXOTHANKEVERYONEWHOHASCONTRIBUTEDTHATBRINGSMETODENNISRITCHIEOURCOLLABORATIONHASBEXNATHINGOFBEAUTYINTHETENYEARSTHATWEHAVEWORKEDTOGETHERICANRECALXONLYONECASEOFMISCOORDINATIONOFWORKONTHATOCCASIONIDISCOVEREDTHATWEBOTHXADWRITTENTHESAMELINEASSEMBLYLANGUAGEPROGRAMICOMPAREDTHESOURCESANDWASASTOUNDEDTOFINDTHATXHEYMATCHEDCHARACTERFORCHARACTERTHERESULTOFOURWORKTOGETHERHASBEENFARGREATERTHANTHEWORKTHATWEXACHCONTRIBUTEDINCOLXEGEBEFOREVIDEOGAMESWEWOULDAMUSEOURSELVESBYPOSINGPROGRAMXINGEXERCISESONEOFTHEFAVORITESWASTOWRITETHESHORTESTSELFREPRODUCINGPROGRAMSINCETHISISANEXERCISEDIVORCEDFROMREALITYTHEUSUALVEHICLEWASFORTRANACTUALXYFORTRANWASTHELANGUAGEOFCHOICEFORTHESAMEREASONTHATTHREELEGGEDRACESAREPOPULARMOREPRECISELYSTATEDTHEPROBLEMISTOWRITEASOURCEPROGRAMTHATWHENCOMPILEDANDEXECUTEDWILLPRODUCEASOUTPUTANEXACTCOPYOFITSSOURCEIFYOUHAVENEVERDONETHISIURGEYOUTOTRYITONYOUROWNTHEDISCOVERYOFHOWTODOITISAREVELATIONTHATFARSURPASXESANYBENEFITOBTAINEDBYBEINGTOLDHOWTODOITTHEPARTABOUTSHORTESTWASIUSTANINCENTIVETODEMONSTRATESKILXANDXETERMINEAWINNERFIGURESHOWSASELFREPRODUCINGPROGRAMINTHECPROGRAMMINGLANGUAGETHEPURISTWILLNOTETHATXHEPROGRAMISNOTPRECISELYASELFREPRODUCINGPROGRAMBUTWILLPRODUCEASELFREPRODUCINGPROGRAMTHISENTRYISMUCHTOOLARGETOWINAPRIZEBUTITDEMONSTRATESTHETECHNIQUEANDHASTWOIMPORTANTPROPERTIESTHATINEXDTOCOMPLETEMYSTORYTHISPROGRAMCANBEEASILYWRITTENBYANOTHERPROGRAMTHISPROGRAMCANCONTAINANARBITRARYAMOUNTOFEXCESSBAGGAGETHATWILXBEREPRODUCEDALONGWITHTHEMAINALGORITHMINTHEEXAMPLEXVENTHECOMXENTISREPRODUCEDX";
        String[] key = FourSquareCipher.generateKey();
        String ciphertext = FourSquareCipher.encrypt(plaintext, key);
        long timeout = 4 * 60 * 1000; // 4 min
        boolean success = false;
        Stopwatch sw = new Stopwatch();

        while (true) {
            String[] foundKey = FourSquareCipherSolver.findKey(ciphertext);
            String text = FourSquareCipher.decrypt(ciphertext, foundKey);
            double score = TextFitnessCalculator.calculate(text);

            System.out.println(String.format("FourSquareCipherSolverTest.java: Score %.2f Decrypted Text: %s", score, text));

            if (plaintext.compareTo(text) == 0) {
                System.out.println(String.format("FourSquareCipherSolverTest.java: Attack is successful. Execution took %d ms.", sw.elapsed()));
                success = true;
                break;
            }

            if (sw.elapsed() > timeout) {
                System.out.println("FourSquareCipherSolverTest.java: Time is up. Attack has failed.");
                break;
            }

        }

        assertTrue(success);
    }
}