package com.github.berkbavas.crypto.attacks.traditional;

import com.github.berkbavas.crypto.ciphers.traditional.FourSquareCipher;
import com.github.berkbavas.crypto.util.Stopwatch;
import com.github.berkbavas.crypto.util.TextFitnessCalculator;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

class FourSquareCipherSolverTest {

    @Test
    void testFindKey() {
        System.out.println("FourSquareCipherSolverTest.java: Test is started.");
        String plaintext = "THEFIRSTSIXTYCHARACTERSISTHESOLUTIONITHANKTHEACMFORTHISAWARDICANTHELPBUTFEELTHATIAMRECEIVINGTHISHONORFORTIMINGANDSERENDIPITYASMUCHASTECHNICALMERITUNIXSWEPTINTOPOPULARITYWITHANINDUSTRYWIDECHANGEFROMCENTRALMAINFRAMESTOAUTONOMOUSMINISISUSPECTXHATDANIELBOBROWXOULDBEHEREINSTEADOFMEIFHECOULDNOTAFXORDAPDPANDHADHADTOSETXLEFORAPDPMOREOVERTHECURXENTSTATEOFUNIXISTHERESULTOFTHELABORSOFALARGENUMBEROFPEOPLETHEREISANOLDADAGEDANCEWITHTHEONETHATBROUGHTYOUWHICHMEANSTHATISHOULDTALKABOUTUNIXIHAVENOTWORKEDONMAINSTREAMUNIXINMANYYEARSYETICONTINUETOGETUNDESERVEDCREDITFORTHEWORKOFOTHERSTHEREFOREIAMNOTGOINGTOTALKABOUTUNIXBUTIWANTXOTHANKEVERYONEWHOHASCONTRIBUTEDTHATBRINGSMETODENNISRITCHIEOURCOLLABORATIONHASBEXNATHINGOFBEAUTYINTHETENYEARSTHATWEHAVEWORKEDTOGETHERICANRECALXONLYONECASEOFMISCOORDINATIONOFWORKONTHATOCCASIONIDISCOVEREDTHATWEBOTHXADWRITTENTHESAMELINEASSEMBLYLANGUAGEPROGRAMICOMPAREDTHESOURCESANDWASASTOUNDEDTOFINDTHATXHEYMATCHEDCHARACTERFORCHARACTERTHERESULTOFOURWORKTOGETHERHASBEENFARGREATERTHANTHEWORKTHATWEXACHCONTRIBUTEDINCOLXEGEBEFOREVIDEOGAMESWEWOULDAMUSEOURSELVESBYPOSINGPROGRAMXINGEXERCISESONEOFTHEFAVORITESWASTOWRITETHESHORTESTSELFREPRODUCINGPROGRAMSINCETHISISANEXERCISEDIVORCEDFROMREALITYTHEUSUALVEHICLEWASFORTRANACTUALXYFORTRANWASTHELANGUAGEOFCHOICEFORTHESAMEREASONTHATTHREELEGGEDRACESAREPOPULARMOREPRECISELYSTATEDTHEPROBLEMISTOWRITEASOURCEPROGRAMTHATWHENCOMPILEDANDEXECUTEDWILLPRODUCEASOUTPUTANEXACTCOPYOFITSSOURCEIFYOUHAVENEVERDONETHISIURGEYOUTOTRYITONYOUROWNTHEDISCOVERYOFHOWTODOITISAREVELATIONTHATFARSURPASXESANYBENEFITOBTAINEDBYBEINGTOLDHOWTODOITTHEPARTABOUTSHORTESTWASIUSTANINCENTIVETODEMONSTRATESKILXANDXETERMINEAWINNERFIGURESHOWSASELFREPRODUCINGPROGRAMINTHECPROGRAMMINGLANGUAGETHEPURISTWILLNOTETHATXHEPROGRAMISNOTPRECISELYASELFREPRODUCINGPROGRAMBUTWILLPRODUCEASELFREPRODUCINGPROGRAMTHISENTRYISMUCHTOOLARGETOWINAPRIZEBUTITDEMONSTRATESTHETECHNIQUEANDHASTWOIMPORTANTPROPERTIESTHATINEXDTOCOMPLETEMYSTORYTHISPROGRAMCANBEEASILYWRITTENBYANOTHERPROGRAMTHISPROGRAMCANCONTAINANARBITRARYAMOUNTOFEXCESSBAGGAGETHATWILXBEREPRODUCEDALONGWITHTHEMAINALGORITHMINTHEEXAMPLEXVENTHECOMXENTISREPRODUCEDX";
        String[] key = FourSquareCipher.generateKey();
        String ciphertext = FourSquareCipher.encrypt(plaintext, key);
        long timeout = 4 * 60 * 1000; // 4 min
        boolean success = false;
        Stopwatch sw = new Stopwatch();

        while (true) {
            String[] foundKey = FourSquareCipherSolver.findKey(ciphertext);
            String text = FourSquareCipher.decrypt(ciphertext, foundKey);
            double score = TextFitnessCalculator.calculate(text);

            System.out.printf("FourSquareCipherSolverTest.java: Score %.2f Decrypted Text: %s%n", score, text);

            if (plaintext.compareTo(text) == 0) {
                System.out.printf("FourSquareCipherSolverTest.java: Attack is successful. Execution took %d ms.%n", sw.elapsed());
                success = true;
                break;
            }

            if (sw.elapsed() > timeout) {
                System.out.println("FourSquareCipherSolverTest.java: Time is up. Attack has failed.");
                break;
            }

        }

        assertTrue(success);
    }
}